# 1.广义线性模型

### 1.1 普通最小二乘
线性回归最小化数据中观察到的响应和通过线性逼近预测的响应之间的残差平方和来拟合系数为$\omega=(\omega_1,\cdots,\omega_p)$的线性模型。从数学上来说，它解决了形式上的问题：  
$$ \min\limits_{\omega}\lVert X\omega - y \rVert_2^2$$
数学推导：
\begin{align*}
\lVert X\omega - y \rVert_2^2&=(X\omega-y)^T(X\omega-y)\\
&=(\omega^TX^T-y^T)(X\omega-y)\\
&=\omega^TX^TX\omega-2\omega^TX^Ty+y^Ty
\end{align*}
对$\omega$求导，得$X^TX\omega-X^Ty$,令其等于0，可以得到系数向量$\omega$的估计值，如下：  
$$\hat{\omega}=(X^TX)^{-1}X^Ty$$
上述公式包含矩阵$\ X^TX$的逆，因此这个估计只在该逆矩阵存在的情况下适用。    


In [54]:
import numpy as np

def ols_fit(X,y):
    Xmat=np.mat(X);ymat=np.mat(y).T
    xTx=Xmat.T*Xmat
    if np.linalg.det(xTx) == 0:
        print('This matrix is singular')
        return
    W=xTx.I*(Xmat.T*ymat)
    return W

### 注意：
普通最小二乘的系数估计依赖于模型项的独立性。当各项具有相关性且设计矩阵x的列具有近似线性相关时，设计矩阵接近于奇异，因此，最小二乘估计变得对所观察到的响应中的随机误差高度敏感，产生大的方差。这种情况可能出现多重共线性。以下将说明这种情况。

当解集$\omega$对X,y的值十分敏感时，那么这样的方程组就是病态的。X称为病态矩阵。仅仅是在X上和y上进行了微小变动，得出的系数值就差异巨大。如下例：

In [62]:
X=[[0,0],[1,1],[2,2]]
y=[0,1,2]
w1=ols_fit(X,y)
X1=[[0,0],[1,1.1],[2,2]]
y1=[0,1,2]
w1=ols_fit(X1,y1)
print('w1 is :\n',w1)
X2=[[0,0],[1,1],[2.1,2]]
y2=[0,1,2]
w2=ols_fit(X2,y2)
print('w2 is :\n',w2)
X3=[[0,0],[1,1.1],[2,2]]
y3=[0,1.1,2]
w3=ols_fit(X3,y3)
print('w3 is :\n',w3)

This matrix is singular
w1 is :
 [[ 1.]
 [ 0.]]
w2 is :
 [[ 0.]
 [ 1.]]
w3 is :
 [[ 0.]
 [ 1.]]


## 梯度下降算法解决这种问题

## 1.2 局部加权线性回归
线性回归的一个问题是有可能出现欠拟合现象，因为它求的是具有最小均方误差的无偏估计。如果模型

## 衡量效果 方差分数
## 优缺点 
优点：结果易于理解，计算不复杂  
缺点：对非线性数据拟合不好  
适用数据类型：数值型和标称型  

## 之后要介绍学习曲线的东西
测试集跟训练集的学习曲线的接近程度   
解释欠拟合，过拟合